notifications:
  email: false

cache:
  directories:
  - "$HOME/krb5-1.14.2"

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
    - os: osx

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io -v krb5-1.14.2:/io/krb5-1.14.2 $DOCKER_IMAGE
    $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/
